Rails.application.routes.draw do
    root to: "welcome#index"
    get    "concerts",                                   to: "concerts#index",       as: "concerts_index"
    get    "concerts/new",                               to: "concerts#new",         as: "concerts_new"
    get    "concerts/:id",                               to: "concerts#show",        as: "concerts_show"
    get    "concerts/:id/edit",                          to: "concerts#edit",        as: "concerts_edit"
    post   "concerts/new",                               to: "concerts#create",      as: "concerts_create"
    patch  "concerts/:id",                               to: "concerts#update",      as: "concerts_update"
    delete "concerts/:id",                               to: "concerts#destroy",     as: "concerts_destroy"
    get    "concerts/:concert_id/reservations",          to: "reservations#index",   as: "reservations_index"
    get    "concerts/:concert_id/reservations/new",      to: "reservations#new",     as: "reservations_new"
    get    "concerts/:concert_id/reservations/:id/edit", to: "reservations#edit",    as: "reservations_edit"
    post   "concerts/:concert_id/reservations/new",      to: "reservations#create",  as: "reservations_create"
    patch  "concerts/:concert_id/reservations/:id/edit", to: "reservations#update",  as: "reservations_update"
    delete "concerts/:concert_id/reservations/:id",      to: "reservations#destroy", as: "reservations_destroy"
    get    "signin",                                     to: "sessions#new",         as: "signin"
    post   "sessions",                                   to: "sessions#create",      as: "sessions"
    delete "signout",                                    to: "sessions#destroy",     as: "signout"
end
